### ISSUE TITLE
Lot's of errors in log when trying npm install

### ISSUE THREAD

**Issue by timothy-kodes** [craigbuckler/gulp-css#2]
I followed your install guide on readme and I get a lot of errors which you can see in the attached log.

I'm on macOS Monterey with node 16.14.0 and npm 8.5.4

[2022-03-15T13_38_20_923Z-debug-0.log](https://github.com/craigbuckler/gulp-css/files/8254003/2022-03-15T13_38_20_923Z-debug-0.log)

**Comment by craigbuckler** [comment]
This is an old repo so it's not surprising you have errors - it's possibly trying to load dependencies which are no longer compatible with recent versions of Node.

While I cannot realistically read your 8,500 line error log, the problem appears to be with [node-gyp](https://www.npmjs.com/package/node-gyp). You could try installing that globally first then try again. If that still fails, you could try adding each `package.json` dependency one by one to work out which is causing an issue then avoid using that.

**Comment by timothy-kodes** [comment]
Yeah tried node-gyp but no luck. Do you still know the node version you built it with? Unfortunately it wasn't declared in the package.json under the "engines" property.  Just curious :)

**Comment by craigbuckler** [comment]
Four years ago it would have been around Node.js 8.0.
I don't recommend returning to that.

**Comment by timothy-kodes** [comment]
Yeah gonna skip that.  I just skim the gulpfile for migrating to gulp 4. Thanks for the very quick reply though !

**Comment by timothy-kodes** [comment]
Managed to get it working by doing the following:

1. `npm install -g npm-check-updates` 
2. `ncu -u`
3. `npm install sass`
4.  added sass -> `sass  = require('gulp-sass')(require('sass')),`
5. and finally changed outputStyle in sasOpts to `compressed` instead of `nested`
`sassOpts: {
      sourceMap       : devBuild,
      outputStyle     : 'compressed',
      imagePath       : '/images/',
      precision       : 3,
      errLogToConsole : true
},`
